### ISSUE TITLE
Handle Root* group types

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#178]
"Root" groups are special groups which are defined in the config and set as the initial group of some new users (may be specific for temp users, or admin, ...).  These groups are web-domain  specific and so config should define the root groups for each served domain. (and probably reject not configured domains?) (so should probably managed in a middleware)

In `app/api/auth/create_temp_user.go:82`, the groupID in which temp user has to be put should be retrieved from the config. (so no retrieval based on `sType`, `sName`, or `sTextId) 

The `groups.sType` `enum('Root','Class','Team','Club','Friends','Other','UserSelf','UserAdmin','RootSelf','RootAdmin')` has be to changed to `enum('Class','Team','Club','Friends','Other','UserSelf','Base')` where (for the migration) all "Root", 'RootSelf','RootAdmin' groups should be changed to "Base".

**Comment by zenovich** [comment]
When the root groups are domain-dependent, it is not obvious how the `authLoginCallback` service should work. On success, it receives the user's id from the login module and checks if it should create a new user or update an existing one. For now, the service does `SELECT ID FROM users WHERE loginID = {id} LIMIT 1`.

When both the root groups and `users` are domain-dependent (meaning that we create a row in the `users` table for each loginID-domain pair), the service probably should also join `users` to `groups_ancestors` with `idGroupParent = {RootSelf_for_domain_id}` to find out which user to work with (the problem here is that `users.sLogin` should be unique, so we cannot have two users with the same login in different domains).

Or, if we want to have domain-independent users, the service should create new group relations if an existing user visits a domain for the first time (with domain-independend users we should think if and where we want to store 'sLastActivityDate' and other domain-dependent columns).

In any case, having multiple root groups in the same database would dramatically increase the number of rows in the `groups_ancestors` table. Also, we should remember that there are root **items** as well which probably should be domain-dependent too causing the similar difficulties with `items_ancestors` if we want to mix data of multiple domains in same tables.

Globally we might question about which data tables are domain-dependent and which are not. As I see it, all (or almost all) of them are domain-dependent so I would suggest creating a separate database for each domain. With per-domain databases we wouldn't have to violate the DRY principle by storing IDs of database objects in the configuration files.

**Comment by smadbe** [comment]
Actually, the way they work with domains with is a bit limited to simple case. They will not duplicate the user for each domain but just use the same. If the user already exists in the db but log in on another domain, you should just add the user's selfGroup to the other root group.
Yeah, there are limits to this, and for actual different websites, they will have to use different databases instead. They are aware of this.
