### ISSUE TITLE
Group permission, step 5: Manager role cleanup 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#317]
The **end goal** will be to implement the group permissions as described in https://france-ioi.github.io/algorea-devdoc/design/access-rights/groups/

Step 5: Manager role cleanup 
Description: 
Remove `users.owned_group_id` and `groups_groups.role`

Subtasks:
* remove `users.owned_group_id` 
   - remove groups matching any `owned_group_id`
   - remove the root_admin_group_id setting and the group itself
   - adapt services (login callback, user delete, get dump, create group check, auth middleware)
   - remove column 
* remove  `groups_groups.role`
  - remove all `groups_groups` with a role != 'member'
  - remove column

**Comment by zenovich** [comment]
> remove the root_admin_group_id setting and the group itself

There can be multiple 'RootAdmin' groups since there can be in use by multiple domain. Probably we should delete all of them. But there is still a question on how to restore them during undo: all the 'RootAdmin' group IDs should be listed somewhere together. But even if we list them, we could not determine which of them to use as a parent for  restored 'UserAdmin' groups :(

**Comment by smadbe** [comment]
"Probably we should delete all of them. " -> 👍 
Don't restore them. When we alter data, quite often the perfect undo-migration is just impossible, that is not a big deal, that is inevitable and the undo is normally not to be used :-)
