### ISSUE TITLE
Unlock allow "can_enter" for explicit-entry items

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#483]
## Motivations
For explicit-entry items, the access for regular users is driven by can_enter_* instead of can_view:content. 

## Tasks
For explicit-entry items, the unlock has to set can_enter_from:1000-01-01.. and can_enter_until:9999-12-31... instead of can_view:content.

**Comment by zenovich** [comment]
Is this task relevant? I'm asking just because we currently have the item_dependencies.grant_content_view flag which tells we should grant the can_view:content on unlocking...
Also, (if we are still going to set can_enter_from) it might be better to set it to LEAST(can_enter_from, NOW()) instead of '1000-01-01...' (?)

**Comment by smadbe** [comment]
Good to ask because such old tasks may be outdated.
But yes, it is still relevant that when we "unlock" access to item (with grant_content_view), IF it is an explicit-entry item, we just allow entering whenever the user wants.
When you say "LEAST(can_enter_from, NOW())", what do you mean? what is the previous value on which you are considering? ah as it may already be unlocked? Yes, it depends if we put NOW() or '1000-01-01...'. I don't know why I put '1000-01-01...', now() makes sense as well, maybe that's better, you're right.
