### ISSUE TITLE
Output group*Progress to zipped csv

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#726]
## Motivations
Allow the user to export the full (non-paged version) of the  group*Progress services to a zipped csv.

As discussed on 10/5 on Slack, let's do it with a specific header.

## Subtasks
* Add a header option to these three service so that the user can get zipped csv of the output instead of json.

**Comment by zenovich** [comment]
After thinking about this again, I suggest adding a query parameter instead of the header option. The reasons are:
1) there is no common content type for zipped csv,
2) it may be difficult for the UI to make request with optional header and return a file as a result.

**Comment by zenovich** [comment]
BTW, do we want to return a zipped csv file or a gzipped csv file?

**Comment by smadbe** [comment]
Check what was done in AlgoreaPlatform. I think zip is more common for regular users.

**Comment by zenovich** [comment]
> Check what was done in AlgoreaPlatform. I think zip is more common for regular users.

```
exec("zip -r ". $file_name . ' ' . $base_dir . ' ' . $groupName . ".csv");
```
https://github.com/France-ioi/AlgoreaPlatform/blob/master/controllers/export_progress.php#L371

**Comment by zenovich** [comment]
As the task turns out to be large, it is probably worth to have a specification before implementing.

The current PHP implementation can work in two modes: the 'root CSV only' mode returning a '{root_group.name}.csv' file and the full mode returning a zip file named '{root_group.name}\_{root_item.text_id}\_{date("Ymd")}.zip'. In both modes the service returns a JSON response `{"file": "{url}"}` where '{url}' points to the newly generated file.

In both modes returned files contain information related to all descendant users of a given root group and visible items from an item subtree starting from a given root item (the root item is included). [Note that the current implementation of our groupUserProgress service supports multiple root items, but it doesn't include root items themselves into the report, nor does it include grandchildren or more distant descendants of the root items.] In both modes the service is synchronous.

The zip file returned by the full mode contains the '{root_group.name}.csv' file which is returned by the 'root CSV only' mode.

The file '{root_group.name}.csv' has the following format:
;{root_item.name};{items[0].name};...
{users[0].login} ({users[0].first_name} {users[0].last_name});{score[0][0]};...
...

The items in the CSV file are ordered by child_order, the users are ordered by last_name and first_name. If there are no results for some item-user pair, the corresponding score is empty (not 0).

Besides the CSV file, the ZIP file returned in the full mode also contains subdirectories reflecting the items subtree with subdirectory names in the format '{items_items.child_order}-{items[i].title}'. Each item subdirectory contains a subdirectories for each user with user logins as their names. Each user subdirectory inside an item subdirectory contains:
1) 'data.json' file with 'score', 'validated', 'finished', 'started_at', 'validated_at', number of hints used, number of corrections read, 'tasks_with_help', number of validated children, number of solved tasks, 'tasks_tried' in the JSON format;
2) for each answer linked to the user-item pair, there is a file named as '{number}-{score}-{answers.id}.{extension}' where the '{extension}' depends on the answer's programming language. If the answer is encoded as JSON in the DB, the file content is the answer's source code, or the answer's tests, or the whole answer encoded as JSON depending on which one is available. Otherwise, the '{extension}' of the answer's file is 'txt' and its content is an error message.

Do we want to implement exactly the same or something different in AlgoreaBackend?

**Comment by smadbe** [comment]
Something different. 
We will need 3 different export: 
1. the csv summary of score
2. 1 + the official submission (the one which scored) subtask
3. 2 + all the answer history 

Let's focus on 1 for now:
- columns: input item id and all its visible children (so 1 level): the item title, for each child prepended with its order (e.g. "1. The first task").
- rows: the users/teams/subgroup (same as the services). Users are encoded in 3 columns (login, lastname, firstname) in the csv
- cell: the score obtained by the user on the item. If no result yet, the cell is empty. 

Notes:
- As the new services almost returns the same as the existing ones (except it miss the item titles), maybe it can be synchronous ?
- For the export, we can assume there is a single "parent_item_id". If you want to make the code common between the export and the existing service, we may consider there is a single  "parent_item_id" as multiple one is not supported nor planned in the UI for now.
- The current service does not return the score of the parent_item_id (only of its children). We'll have to add as we have to know the total score computed by the platform (the frontend cannot even compute it easily). (in a different issue or in the same if you want to share the code as much as possible.

**Comment by zenovich** [comment]
> Let's focus on 1 for now:
>
> columns: input item id and all its visible children (so 1 level): the item title, for each child prepended with its order (e.g. "1. The first task").
rows: the users/teams/subgroup (same as the services). Users are encoded in 3 columns (login, lastname, firstname) in the csv
cell: the score obtained by the user on the item. If no result yet, the cell is empty.

Should it be three separate csv files (for users, team, subgroups) zipped together?

**Comment by zenovich** [comment]
> The current service does not return the score of the parent_item_id (only of its children). We'll have to add as we have to know the total score computed by the platform (the frontend cannot even compute it easily). (in a different issue or in the same if you want to share the code as much as possible.

How to combine this with pagination? (Currently we have json array row for each table cell, and we paginate by rows, i.e. child items. So if we mix parent and child items together, the page can end right after a parent item while its children are on the next).

**Comment by smadbe** [comment]
> Should it be three separate csv files (for users, team, subgroups) zipped together?

3 different services.

> How to combine this with pagination? (Currently we have json array row for each table cell, and we paginate by rows, i.e. child items. So if we mix parent and child items together, the page can end right after a parent item while its children are on the next).

We paginate by row, so users/teams/groups.

**Comment by smadbe** [comment]
For making it clearer, I'll create a new issue when I'll have all the info.
