### ISSUE TITLE
Find solution to allow editing children when the propagation is too long

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#838]
## Overview

It is very common to add a new chapter as a child to a chapter close to the public root items (for instance in item `4702`). This is currently not doable through the UI / curl as the propagation takes too long and the request times out... and so the change is reverted.

The only way to add such a chapter now is to add it by hand in the DB, mark the propagation and run the propagation by hand.. this is both painful and dangerous.

## Proposal

Propagation affecting other users such as adding a chapter in another chapter could be done in "background". There is "no reason" to wait for the end of the propagation to respond to the current user that the children list has been updated.

So you should mark the propagation as to be done, respond to the request as a success, and then launch the propagation "in background" (in a safe way) as this propagation does not take so much time for the moment (a few minutes for the longer).

Note that if "respond success and continue processing" is difficult with the current lib, a "easy" way to do it with our current deployment setup is to run processing [as a sql trigger in AWS Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Lambda.html). In this case, you just have to define what needs to be called as executable file (for instance `AlgoreaBackend db-recompute` or a specific executable file).

## Acceptance criteria
- [x] Make a proposal before implementing it

**Comment by GeoffreyHuck** [comment]
[Proposal not finished yet]

### Remark on transactions and propagation

Currently, the propagation is made in the same transaction as the creation/update of items. This can create deadlock issues because with InnoDB, **all the locks** that are acquired inside a transaction are only released at the end of the transaction (source: High Performance MySQL - O'Reilly). Thus, the more things we do inside a transaction, the more locks we acquire, and the higher the probability that we face a deadlock with other concurrent transactions.

When everything we want is updated but the propagation has not been made yet, the database is in a consistent state. The propagation is a transformation from a consistent state to another consistent state. So, we can end the transaction there, and start a new transaction for the propagation.

> We should run each propagation in its own transaction where only the propagation is done.

It also simplifies the implementation of async propagation.

### Notes on concurrent propagations

The propagation is time consuming and is inside a big transaction. It may acquire many locks until it completes. It may be possible to break it down into smaller chunks but for now we have no reason to assume we need to do that. We can consider this if we find that some transaction from another place that is not a propagation, deadlocks with a transaction of a propagation.

But, there is evidence that a deadlock between two propagations can happen (https://github.com/France-ioi/AlgoreaBackend/issues/913).

> The safest would be to make sure that a propagation can never be run more than once concurrently.

Do do that, we could either:
- Use a list and call the propagations sequentially. But this would require to have a system that handles a list
- Acquire a lock at the beginning of the propagation transaction, and release it at the end. If another propagation is called concurrently, it will wait for the lock to be released and run after. There is a possibility that we end up with a lot of concurrent propagations waiting for the lock.
`Warning: If that's a serious issue, we need to consider what to do in this case.`


### How to execute the propagation

[TODO]

**Comment by smadbe** [comment]
👍 
Additional remarks: 

* I am not sure you mention it but an important point is that "propagation" has no argument, it just process "todos" in the propagation table. So in practice, it means that if there is no point of having 2 propagations queued (not started) as the first one will treat the second one. 

* For the same reason, we could even consider to "abort" a running propagation if there is another propagation request 

* In the same way, if I am remembering correctly, the propagation is just an iterative process which pull propagation to be done and push another propagations to be done (in a way we are sure it ends one day). So, we could consider that the propagation commits and exits its transaction every 5sec (and then relaunch to continue) so that we prevent deadlocks and handle new propagation request.

Does it seem correct to you @GeoffreyHuck ?

For the way to run it, I would find cleaner to have a kind of independent process (that we could also run after having done a manual change in the db for instance) that would handle propagation in the best way: it may uses a timeout as described above not to block the service, it would not run in parallel but could run until there are no propagation anymore (so possibly run almost in continuously when there are a lot of changes), ... there are many different pattern we could use, I am not convinced by "running in the service after it has sent the response" but that could be a good easy solution as first... if it works ;-) maybe the easiest is to test ourselves.

**Comment by GeoffreyHuck** [comment]
Yes, it looks as you describe it:
1. Check what needs to be updated
2. Update it
3. Set what needs to be updated for the next step (the children)
4. Loop until there is nothing to update

So, we could split each of those steps into a smaller transaction. If we need too.


### Running the propagation Continuously or Triggered by code?

**Continuously pros:**
- We cannot forget to run the propagation
- We can add a propagation in the DB manually
- We can limit to 1 the number of concurrent calls with Lambda: https://aws.amazon.com/about-aws/whats-new/2017/11/set-concurrency-limits-on-individual-aws-lambda-functions/ . So that if a propagation is already running, it will not run another at the same time.

**Continuously cons:**
- Running the lambda every second implies higher AWS cost per instance (how much? does it matter?)
- I'm not sure how Lambda works, but maybe we need to implement security checks to call the service

**Triggered by code pros:**
- We only run the propagation when needed, so no additional AWS cost per instance (how much? does it matter?)
- No need to implement security checks to call the service

**Triggered by code cons:**
- If we need to add a propagation in DB manually, we need a way to run the propagation, either via a command or by updating the right item
- We need to be sure we never forget to run the propagation when needed
- We need to be sure that the solution to run after sending the response works with Lambda
- We need to make sure the propagation can only be called once concurrently, but it is not difficult

* If we choose the Continuous method, we need to know the cadence: **every 1s ? every 5s ?**
* We need to know what the AWS cost would be, and remember that the cost have to be multiplied by the number of instance.

Note: If we have any other task that needs to be performed regularly in the future, we can group them in the same lambda. It's equivalent has having a cron job running every second to check if there is something to do, which is a common low-cost solution to handle the problem of periodic tasks.



### Running the propagation one step at a time or in one go?

One step pros:
- Smaller transactions, but we have no reason to believe it matters because we never had deadlocks between a propagation and something else

One go pros:
- Faster because we don't have to wait for X runs

**Comment by smadbe** [comment]
Set of remarks (before maybe just discussing everything):
- AWS Lambda is not "designed" for being called every seconds (even if it could work). 
- If the lambda is a different function (if should be if it requires some concurrency config), it would not require any addition security as it would not be connected to a http endpoint
- There is a way to trigger SNS event from RDS (called by a SQL trigger for instance... so when there is a new pending propagation), and that's basic to call a lambda from a SNS event... so I think that should be the easiest and cleanest way to go (for now at least).
- If the propagation is iterative and each iteration (or set of iterations?) can be run in a separate transaction (acceptable overhead?): we could use transaction priority (weight?) to always prioritize http-related queries over propagation (even if it was "scheduled" earlier).  

Combining these last two remarks, I think we could have a very smooth, transparent, cheap and efficient propagation mechanism.

**Comment by GeoffreyHuck** [comment]
### Solution retained
Calling the propagation with Lambda, using the app binary with a command argument, from inside a MySQL trigger

### Trade-offs
**pros:**
- call the propagation only when needed
- no need to check the security of the call because it is not made via HTTP
- works if a propagation is added manually in the database

**cons:**
- Increases the dependence to AWS
- Might be a bit difficult to test

### Detail of the process
- We add a AWS Lambda call inside a MySQL trigger, using something similar as here: https://gist.github.com/alexcasalboni/89954974f90e7e05c4b52cc8b0c790de
- The Lambda call must be made only when a propagation is added while the propagation table is empty. This check must also be fast. **This must be tested.**
- Lambda will execute the binary with a "propagation" command argument (with the same technique used for the db-migrate command)

### 
- The propagation's is currently done in one big transaction. It will be split into smaller transactions: each "turn" will be a different transaction
- We will test the case that caused the propagation to be very long before and after the change to validate that splitting the transaction doesn't produce a performance hit, although we expect it to be slightly faster
- We must guarantee that no problem will occur if the propagation process is ever called concurrently, even if that shouldn't happen
- We must have a way to know if the process is killed because it takes too long (current limit on Lambda calls are currently set to 15min)

### Documentation of the propagation process
- We want to know its time complexity: how many "turns", and how many rows can be affected in the worst case
- We want to know what tables and rows are locked during the process, so we can know what could cause the propagation transaction to deadlock.

**Comment by smadbe** [comment]
When changing status to "Blocked", try to always drop a line here on what is blocking. For instance, here I don't see.

**Comment by GeoffreyHuck** [comment]
The PR was merged: https://github.com/France-ioi/AlgoreaBackend/pull/999

Has it been tested? Can we close this issue?

**Comment by smadbe** [comment]
As it was merged, it can be closed anyway.
Yes, it is currently running on one of our instances.
