### ISSUE TITLE
Item navigation: do not return activities as skill children

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#959]
## Motivations

In the frontend, the navigation service is used for the left menu. However, this left menu for skills only display skills, not children activities. Activities are currently filtered client-side but properties such as `has_visible_children` is still wrong, and so give "strange" behaviors.

## Subtasks
In the item navigation service: 
- if the id given as input is a skill, only return skills (if it is a chapter, returns tasks and chapter... but it is already the only possible children)
- `has_visible_children` should be computed on children skills only.

**Comment by GeoffreyHuck** [comment]
"has_visible_children should be computed on children skills only."

It means, if the given id is a skill, only compute `has_visible_children` on its children of type Skill, but if it is a chapter, compute `has_visible_children` on its children of type Chapter and Task, or all because it cannot have a Skill have a child. Correct?
