### ISSUE TITLE
Remove `is_owner` from `permissions_generated` + fix legacy

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#966]
As discussed in #851 (related with #852 as well), `is_owner` should be removed from `permissions_generated` as it is not generated and can be used directly from `permissions_granted` as there is no propagation.

Side task:
From #851 and #852, there seems to be some issues with legacy data, so create a migration that will re-put computed permission to max (and mark for propagation) the group-item where the group is owner.

**Comment by GeoffreyHuck** [comment]
I found out that:
- `permissions_generated` primary key is `(group_id, item_id)`
- `permissions_granted`primary key is `(group_id, item_id, source_group_id, origin)`

So I imagine, though I'm not sure, that it's possible for `permissions_granted` to have many rows for a `(group_id, item_id)` pair, one or multiple of which could have `is_owner=1`. If that's correct, we would have to use aggregation on `permissions_granted` to know whether we have `is_owner=1`, instead of just having a join.

It may be easier to keep `is_owner_generated` instead, what do you think?

**Comment by smadbe** [comment]
Hum yes, that's probably the reason it was in "generated" I was looking for. Ok, let's keep it then.
