### ISSUE TITLE
Docfixes related to thread services

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#988]
1) Question: why "token" not required in `threadGet`? 

There might be a reason but it seems not obvious as I cannot guess it immediately. It may make sense to add the reason in the service description, otherwise I don't know what to do with not-set `token`.

2) `threadUpdate`

![Screenshot 2023-08-07 at 12 33 29](https://github.com/France-ioi/AlgoreaBackend/assets/1053150/63ea9b8d-01a8-4202-af2f-e7128f9cd2a8)

`ItemID` and `ParticipantID` does not follow the convention of camel case for the backend.  As there are given in the url, I assume the itemID and participantID do not have to be given in body anyway I assume.

3. In `threadGet`, I would find useful to describe what is in the token.

4. Some services have `can_request_help_to` `appears only in services that support this permission (see service description), and only if it is set`. I would expect the value to be `null` when it is set but the permission not given to the user. It is not clear if it is valid value as the field is not indicated as `nullable`. Anyway, shouldn't it be an array as we cannot aggregate groups? 

5. `threadGet`: there is probably a line break missing in `the thread hasn't been started Restrictions:` 

6. In the swagger doc, the "thread" section disappear from the menu as soon as you click on another service, for instance [this one](https://franceioi-algorea.s3.eu-west-3.amazonaws.com/spec/v1.10.0.html#tag/group-memberships/operation/groupRemoveMembers). Swagger bug or something bad in the metadata?

6. Unlike most other services,`threadGet`, `listThreads`, `threadUpdate` do not clearly state what happens if validations or restrictions are failing.

**Comment by GeoffreyHuck** [comment]
PR here with all points but 4: https://github.com/France-ioi/AlgoreaBackend/pull/995

Regarding point 4,

4. Some services have `can_request_help_to` `appears only in services that support this permission (see service description), and only if it is set`. I would expect the value to be `null` when it is set but the permission not given to the user. It is not clear if it is valid value as the field is not indicated as `nullable`. Anyway, shouldn't it be an array as we cannot aggregate groups? 

Strictly speaking it should be an array. It's not because for now it has only been implemented without aggregation.

But this comes with an issue, with the current technique, we cannot represent a `null` permission differently than by removing the field from the answer. So we cannot distinguish whether there is no permission (field is null because there is no permission), or whether the service doesn't support this permission (field is null because the permission is not set).

Transforming this field to an array can solve the issue: we can represent "no permission" with an empty array, and remove the field completely when the service doesn't support it, removing the confusion altogether.

**Comment by GeoffreyHuck** [comment]
Some remarks after further verification:
- `granted_via_group_membership`, `granted_via_item_unlocking`, `granted_via_other` and `granted_via_self` are aggregations on `group` with groupID+ancestors.
- `granted` is not an aggregation, it is the entry with given `groupID`, `origin=group_membership` and given `sourceGroupID`

I create the issues.

**Comment by GeoffreyHuck** [comment]
`6. In the swagger doc, the "thread" section disappear from the menu as soon as you click on another service, for instance [this one](https://franceioi-algorea.s3.eu-west-3.amazonaws.com/spec/v1.10.0.html#tag/group-memberships/operation/groupRemoveMembers). Swagger bug or something bad in the metadata?`

-> An issue was created specifically for this: https://github.com/France-ioi/AlgoreaBackend/issues/1029

**Comment by GeoffreyHuck** [comment]
I checked why this issue was still open:
- The issue related to swagger is not fixed, I created a specific issue for it: #1029 
- Regarding my comment where I say I create an issue: https://github.com/France-ioi/AlgoreaBackend/issues/988#issuecomment-1707849061 . It was actually Damien who created the issue here: #1004 . The PR has already been merged.

So I close this issue now.
